### PR TITLE
Fix GUI crash

### PR DESCRIPTION
**Pull request by mrexodia**
Added GitHub Actions https://github.com/mrexodia/ClawSearch/actions/runs/3204860428

And if you push a tag it will automatically create a release: https://github.com/mrexodia/ClawSearch/releases/tag/2022-10-07

### CODE REVIEW

**Comment by mrexodia** [comment]
Would be cool if you could add the `hacktoberfest` label to your repo so it counts for https://hacktoberfest.com/

**Comment by codecat** [comment]
Looks great, thank you! 🎉

**Comment by mrexodia** [comment]
Thanks for the quick merge! Would be cool if you could create a release tag as well.

**Comment by codecat** [comment]
Done! Thanks for the reminder: https://github.com/codecat/ClawSearch/releases/tag/2022-10-08

**Pull request merged**
